# Generated by Django 5.2 on 2025-06-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
